builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - image_templates: ["ghcr.io/siiimooon/{{ .ProjectName }}:{{ .Version }}"]
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/siiimooon/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/siiimooon/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
docker_manifests:
  - name_template: ghcr.io/siiimooon/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/siiimooon/{{ .ProjectName }}:{{ .Version }}