project_name: istio-ca-step-shim
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - image_templates: ["ghcr.io/siiimooon/istio-ca-shim-step:{{ .Version }}"]
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/siiimooon/istio-ca-step-shim
      - --label=org.opencontainers.image.source=https://github.com/siiimooon/istio-ca-step-shim
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}