apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "istio-ca-shim-step.fullname" . }}
  labels:
    {{- include "istio-ca-shim-step.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "istio-ca-shim-step.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "istio-ca-shim-step.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - "/istio-ca-shim-step"
          {{- if .Values.ca}}
          {{- if .Values.ca.url}}
          - "--ca-url"
          - "{{ .Values.ca.url }}"
          {{- end }}
          {{- if .Values.ca.fingerprint}}
          - "--ca-fingerprint"
          - "{{ .Values.ca.fingerprint }}"
          {{- end }}
          {{- end }}
          {{- if .Values.loglevel }}
          - "--loglevel"
          - "{{ .Values.loglevel }}"
          {{- end }}
          {{- if .Values.tls.enabled }}
          - "--tls-crt"
          - "/tls/tls.crt"
          - "--tls-key"
          - "/tls/tls.key"
          {{- end }}
          ports:
            - name: grpc
              containerPort: 9696
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            tcpSocket:
              port: grpc
          readinessProbe:
            tcpSocket:
              port: grpc
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      {{- if .Values.tls.enabled }}
          volumeMounts:
            - mountPath: /tls
              name: tls
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName }}
      {{- end }}