apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-ca-shim-step.fullname" . }}
  labels:
    {{- include "istio-ca-shim-step.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9696
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "istio-ca-shim-step.selectorLabels" . | nindent 4 }}
